### ISSUE TITLE
Is this project working? If so, this is exciting! I'm going to give it a try

### ISSUE THREAD

**Issue by ggzzzzz628** [imsoo/fight_detection#3]
Is this project working? If so, this is exciting! I'm going to give it a try

**Comment by ggzzzzz628** [comment]
What is the velocity going to be? Can the CPU run?

**Comment by imsoo** [comment]
@gzchenjiajun, Hi

Thank you for your interest in this repo.

> Is this project working? If so, this is exciting! I'm going to give it a try

Yes. Please let me know if you have any trouble in try it. I'll help you.

> What is the velocity going to be? Can the CPU run?

Yes, but I recommend using a GPU.

**Comment by ggzzzzz628** [comment]
So what's the velocity going to be? Is there a base indicator? thank you    @imsoo

**Comment by imsoo** [comment]
> So what's the velocity going to be? Is there a base indicator?

#4
