### ISSUE TITLE
values and units of features

### ISSUE THREAD

**Issue by stan-lu** [imsoo/fight_detection#9]
What's the unit of Δpoint? Is it presented as number of pixels? If so, may I ask why it is not normalized by the width and height of the video? I believe it will be more robust if it is irrelevant to the size of the video.
And I assume that the units of angle and Δangle are degrees but not rads. Is that correct?

**Comment by imsoo** [comment]
@stan-lu 

Thank you for your interest in this repo.

---

> What's the unit of Δpoint? Is it presented as number of pixels? 

It is the distance in 2D position. (From the previous postion to the current position)

> If so, may I ask why it is not normalized by the width and height of the video? I believe it will be more robust if it is irrelevant to the size of the video.

It just didn't occur to me. I agree with your idea. I think it's also a good idea to normalize with each person's height.

> And I assume that the units of angle and Δangle are degrees but not rads. Is that correct?

Yes, it is degree.

---

**Comment by stan-lu** [comment]
@imsoo Got it. Thank you! I will try changing my video to the size of that in your training dataset to see if the result will be better.
Is that 640 x 480?

**Comment by imsoo** [comment]
@stan-lu 

I'm not sure what the result will be. 

The size of the videos for training data set is as follows.

>MHAD Dataset : 640 x 480
CMU Panoptic Dataset : 720 x 480
